apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment01
spec:
  replicas: 2
  selector:
   matchLabels:
    app: run-pods

  template: 
   metadata:
     labels:
      app: run-pods
   spec:
    containers:
     - name: capstonecontainer
       image: creatorshubham/capstone:v.22

---

apiVersion: v1
kind: Service
metadata:
  name: new-service
  labels:
   svc: new-svc
spec:
  selector:
    app: run-pods
  ports: 
    - port: 5000
      targetPort: 5000
      nodePort: 31000
  type: NodePort

